### PR TITLE
Add diff and why subcommands — session comparison and causal chain tracing

### LINKED ISSUE #4: v0.5.0: Session diff + causal chain (why)
## Problem

AI agents are non-deterministic. The same prompt, the same codebase, the same model — and you get different results. Sometimes the agent succeeds in 90 seconds. Sometimes it spins for 4 minutes and fails. You have no systematic way to answer:

- "What did the agent do differently this time?"
- "Why did the agent decide to refactor that file instead of just fixing the bug?"
- "The agent worked yesterday. What changed?"

Today, answering these questions means manually reading through two session replays side by side and trying to spot the divergence. That is slow, error-prone, and does not scale when sessions have hundreds of events.

The missing primitive is a structural diff: a way to compare two sessions at the behavioral level — not as raw text, but as aligned sequences of phases, decisions, and outcomes.

---

### `agent-strace diff <session-a> <session-b>`

Structural diff of two sessions. Not a line-by-line text diff. A behavioral diff that aligns phases, finds the divergence point, and explains what changed.

**How it works:**
1. Run `explain` on both sessions to produce phase lists
2. Align phases using longest common subsequence on phase names and tool call patterns
3. Find the first phase where behavior diverges (different files read, different commands run, different outcome)
4. For each divergent phase, show: what each session did, what files differed, what commands differed, and the downstream effect on cost and duration

```bash
agent-strace diff abc123 def456

# Side-by-side in terminal (uses terminal width)
agent-strace diff abc123 def456 --side-by-side

# JSON output for programmatic use
agent-strace diff abc123 def456 --format json

# Include in HTML share output
agent-strace share abc123 --diff def456
```

**Example output:**

```
Comparing: abc123 (4m 12s, $4.20) vs def456 (1m 45s, $1.80)

Phases 1–1: identical
  Both: Read AGENTS.md, Read pyproject.toml

Diverged at Phase 2 (0:05 into session):

  abc123                              def456
  ──────────────────────────────────  ──────────────────────────────────
  Read: requirements.txt              Read: pyproject.toml
  Ran: pip install psycopg2           Ran: uv sync
  Result: failed (missing libpq-dev)  Result: success
  Retried: 3 times                    Retried: 0 times

  abc123 read requirements.txt first (stale, missing libpq-dev)
  def456 read pyproject.toml first (current, correct dependencies)

Phase 3 onwards: only abc123 (def456 completed at Phase 2)
  abc123: 3 recovery phases, all failed

Summary:
  abc123: 4m 12s, 47 events, ~$4.20, 3 retries, failed
  def456: 1m 45s, 19 events, ~$1.80, 0 retries, succeeded

  Time difference:  +2m 27s  (abc123 took 2.4× longer)
  Cost difference:  +$2.40   (abc123 cost 2.3× more)
  Root divergence:  Phase 2 — file read order determined dependency resolution path
```

---

### `agent-strace why <session-id> <event-id>`

Trace backwards from any event to reconstruct the causal chain. Answers "why did the agent do this?" by following the dependency links between events.

**Causal link rules:**
- `tool_call` immediately after `error` → caused by the error (retry or recovery)
- `file_write` after `file_read` of the same path → read informed the write
- `tool_call` referencing a path or value from a preceding `tool_result` → result informed the call
- `tool_call` after `user_prompt` with no intervening events → prompt directly caused the call
- `tool_call` after `assistant_response` → response planned the call

Walk backwards through the causal chain until reaching a `user_prompt` or `session_start`.

```bash
agent-strace why abc123 47
agent-strace why abc123 47 --format json
```

**Example output:**

```
Why did event #47 happen?

#47  Write src/auth.py  (added missing import)
 ← caused by #38  tool_result: pytest failed
                  "ImportError: cannot import name 'auth_utils'"
   ← caused by #37  tool_call: uv run pytest
     ← caused by #22  Write src/auth.py  (refactored function signature)
       ← caused by #7   user_prompt: "fix the auth module"

Root cause: user_prompt #7
Causal depth: 4 steps
```

---

## Implementation

**New files:**
- `src/agent_trace/diff.py` — phase alignment, divergence detection, diff formatting
- `src/agent_trace/why.py` — causal chain reconstruction

**Depends on:** `explain.py`, `cost.py`

**CLI additions:**
```
agent-strace diff <session-a> <session-b> [--side-by-side] [--format json|table]
agent-strace why <session-id> <event-id> [--format json|text]
```

**Phase alignment algorithm:**
- Use LCS on phase name tokens (split on whitespace, ignore stop words)
- Fall back to positional alignment if LCS produces poor results (< 50% match)
- Mark unmatched phases as "only in A" or "only in B"

**Tests:** ~18 new tests covering phase alignment (identical sessions, fully divergent sessions, partial overlap), causal chain reconstruction (direct cause, multi-step chain, no causal link found), and diff formatting.

**Constraints:**
- Zero new dependencies
- Must handle sessions of different lengths gracefully (one session may have more phases)
- `why` must handle events with no causal link (return "no causal link found" rather than erroring)
- Diff output must fit in 80-column terminals by default; `--side-by-side` requires wider terminal

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
Closes #4

## What

Two new subcommands for understanding *why* a session behaved the way it did and *how* it differed from another session.

## Changes

**`diff.py`** (new):
- `diff_sessions(store, session_a, session_b)` — aligns phases from both sessions via LCS (longest common subsequence) on phase labels, then reports per-phase differences: files only in A, files only in B, commands only in A/B, failed vs passed outcomes
- `format_diff()` — shows divergence point and per-phase delta

**`why.py`** (new):
- `build_causal_chain(events, target_index)` — walks backwards from a target event using: `parent_id` links (tool_result → tool_call), error→retry detection, path-reference matching (tool_result text containing a path referenced by a later tool_call), and `user_prompt` as the root cause terminator
- `format_why()` — renders the chain root → target with reasons at each link

**CLI additions:**
- `agent-strace diff <session-a> <session-b>`
- `agent-strace why [session-id] <event-number>` (1-based, matches replay output)

## Example output

```
Comparing: abc123 vs def456

Diverged at phase 2:

  Phase 2: run tests
    abc123 only:  $ python -m pytest
    def456 only:  $ uv run pytest

  abc123: 4m 12s, 47 events, 8 tools, 2 retries
  def456: 2m 05s, 31 events, 5 tools, 0 retries
```

```
Why did event #4 happen?

  #  4  tool_call: Bash  $ pytest tests/

Causal chain (root → target):

    #  1  user_prompt: "run the test suite"
       (prompt at #1 triggered this)
  ←  #  3  error: exit 1
       (retry after error at #3)
  ←  #  4  tool_call: Bash  $ pytest tests/
```

## Tests

20 new tests (192 total passing)

### CODE REVIEW

File: src/agent_trace/why.py [hunk 1]
```diff
@@ -0,0 +1,248 @@
...
+            _walk(parent_idx, f"← parent of #{idx + 1}")
+            return
+
+        # 2. Scan backwards for the most recent causal predecessor
+        target_paths = _event_paths(event)
+
+        for prev_idx in range(idx - 1, -1, -1):
+            prev = events[prev_idx]
+
+            # Error → next tool_call is a retry
```
Comment (Siddhant-K-code) [inline src/agent_trace/why.py]: **False positive: error→retry rule fires on any ERROR before any TOOL_CALL, not just adjacent ones.**

The backwards scan hits the first `ERROR` it finds and immediately attributes the target `TOOL_CALL` to it, regardless of how many unrelated events are between them. A session like:

```
#1 user_prompt: "run tests"
#2 tool_call: Bash $ pytest        ← fails
#3 error: exit 1
#4 tool_call: Bash $ git status    ← unrelated, but scan hits #3 first
#5 tool_call: Bash $ pytest        ← actual retry
```

`why #5` correctly links to `#3`. But `why #4` also links to `#3` even though `git status` is not a retry — it's the next command after the error. The rule should only fire if the error is the *immediately preceding* event (or at most separated by a `tool_result`).
